{% set name = "datatable" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datatable-{{ version }}.tar.gz
  sha256: 3c3a7d3bee3c463a36fe77c5d4747278a741c23fc6c6e2dba110deec200502ba

build:
  number: 0
  skip: true  # [py<35 or win]

# numpy and pandas are _optional_ dependencies of dataframe
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - datatable
  files:
    - setup.cfg
  source_files:
    - src
    - tests
    - tests_random
    - LICENSE
  commands:
    - rm tests/test-docs.py
    - pytest tests -k 'not test_fread_from_cmd2 and not test_dt_version'
  requires:
    - pip
    - numpy
    - pandas
    - xlrd
    - pytest >=3.1
    - pytest-cov
    - docutils >=0.14

about:
  home: https://github.com/h2oai/datatable
  summary: Python library for fast multi-threaded data manipulation and munging.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeromebaum
